# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YquvpD0KNbk2Mhck9bChfeaubI3YRJ4k
"""

import numpy as np
from scipy.stats import skew, kurtosis

def calculate_moments(data):
    """
    Calculate the first four moments of a sample dataset.

    Parameters:
    data (array-like): Sample values representing a random variable.

    Returns:
    tuple: A tuple containing (mean, variance, skewness, kurtosis)
    """
    # Convert the data to a NumPy array
    data = np.array(data)

    # First Moment (Mean)
    mean = np.mean(data)

    # Second Moment (Variance)
    variance = np.var(data, ddof=1)  # Using ddof=1 for sample variance

    # Third Moment (Skewness)
    skewness = skew(data)

    # Fourth Moment (Kurtosis)
    kurt = kurtosis(data)  # This returns excess kurtosis, so we do not add 3

    return mean, variance, skewness, kurt

# Example usage with a sample dataset
if __name__ == "__main__":
    # Sample dataset (could be any observations, e.g. from your AI model outputs)
    sample_data = [12, 15, 12, 10, 13, 14, 15, 10, 10, 11, 16, 20, 18]

    mean, variance, skewness, kurtosis = calculate_moments(sample_data)

    # Output the results
    print(f"Mean: {mean:.2f}")
    print(f"Variance: {variance:.2f}")
    print(f"Skewness: {skewness:.2f}")
    print(f"Kurtosis: {kurtosis:.2f}")